KEYWORDS = [
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "String",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "void",
    "volatile",
    "while",
]

PATTERNS = {
    "comment": r"(\/\/).*",
    "delimiter": r"\[|\]|\(|\)|,|\{|\}|;|\.",
    "identifier": r"\b[a-zA-Z_][a-zA-Z0-9_]*\b",
    "literal": r"\b\d+(\.\d+)?\b",
    "operation": r"\+|\-|\*|(\/)|\=|\==|\!=|\<|\>",
    "string_literal": r'"([^"]*)"',
}
